name: Build Flutter APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: سحب الكود
        uses: actions/checkout@v4

      - name: إعداد Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          channel: 'stable'

      - name: حذف مجلد Android القديم
        run: rm -rf accounting_ledger/android

      - name: إنشاء مجلد Android جديد
        run: |
          cd accounting_ledger
          flutter create --platforms=android .

      - name: تثبيت الحزم
        run: |
          cd accounting_ledger
          flutter pub get

      - name: بناء APK
        run: |
          cd accounting_ledger
          flutter build apk --release

      - name: رفع APK
        uses: actions/upload-artifact@v4
        with:
          name: my-app-apk
          path: accounting_ledger/build/app/outputs/flutter-apk/app-release.apk
